-- Calculateur de note configurable par matière : colonne grading (JSON : épreuves, poids, 2e chance).
-- Rejouable.

alter table public.matieres add column if not exists grading jsonb;

-- Formules des six matières d'origine, appliquées seulement si grading est encore vide.
update public.matieres set grading = $j${"items": [{"id": "q1", "label": "CC1 — QCM 1 (10 %)", "weight": 10}, {"id": "q2", "label": "CC1 — QCM 2 (15 %)", "weight": 15}, {"id": "cc2", "label": "CC2 — devoir (30 %)", "weight": 30}, {"id": "cc3", "label": "CC3 — programmes (35 %)", "weight": 35}], "second": {"id": "cc4", "label": "CC4 — 2e chance (10 %)", "required": true, "weight": 10}, "formule": "Note = 10 % × max(QCM1, CC4) + 15 % × max(QCM2, CC4) + 30 % × max(CC2, CC4) + 35 % × max(CC3, CC4) + 10 % × CC4  (validée si ≥ 10)"}$j$::jsonb where id = 'algo1' and grading is null;
update public.matieres set grading = $j${"items": [{"id": "c1", "label": "CCI1 — Systèmes (5 %)", "weight": 5}, {"id": "c2", "label": "CCI2 — Systèmes (20 %)", "weight": 20}, {"id": "c3", "label": "CCI3 — Architecture (25 %)", "weight": 25}], "second": {"id": "c4", "label": "CCI4 — 2e chance (50 %)", "required": true, "weight": 50}, "formule": "Note = 5 % × max(CCI1, CCI4) + 20 % × max(CCI2, CCI4) + 25 % × max(CCI3, CCI4) + 50 % × CCI4"}$j$::jsonb where id = 'bas' and grading is null;
update public.matieres set grading = $j${"items": [{"id": "n1", "label": "Note 1 (TD)", "weight": 1}, {"id": "n2", "label": "Note 2 (TD)", "weight": 1}, {"id": "n3", "label": "Note 3 (amphi)", "weight": 1}], "second": {"id": "n4", "label": "Note 4 — 2e chance (facultative)"}, "formule": "Sans note 4 : (N1 + N2 + N3) / 3. Avec note 4 : (max(N1,N4) + max(N2,N4) + max(N3,N4)) / 3"}$j$::jsonb where id = 'bases2' and grading is null;
update public.matieres set grading = $j${"items": [{"id": "cc1", "label": "CC1 — interro (15 %)", "weight": 15}, {"id": "cc2", "label": "CC2 — moyenne des 2 interros (40 %)", "weight": 40, "parts": [{"id": "cc21", "label": "CC2.1 — interro (20 %)"}, {"id": "cc22", "label": "CC2.2 — interro (20 %)"}]}, {"id": "cc3", "label": "CC3 — devoir amphi (45 %)", "weight": 45}], "second": {"id": "cc4", "label": "CC4 — 2e chance"}, "formule": "CC2 = moyenne des 2 interros. Note = 15 % × max(CC1, CC4) + 40 % × max(CC2, CC4) + 45 % × max(CC3, CC4)"}$j$::jsonb where id = 'calc1' and grading is null;
update public.matieres set grading = $j${"items": [{"id": "c1", "label": "CC1 — QCM partie A", "weight": 1}, {"id": "c2", "label": "CC2 — QCM partie B", "weight": 1}], "second": {"id": "c3", "label": "CC3 — 2e chance (facultative)"}, "formule": "Note = 0,5 × max(CC1, CC3) + 0,5 × max(CC2, CC3)  (notes plafonnées à 20)"}$j$::jsonb where id = 'sn' and grading is null;
update public.matieres set grading = $j${"items": [{"id": "c1", "label": "CC1 — poster + oral (/40)", "weight": 35, "max": 40}, {"id": "c2", "label": "CC2 — QCM + rapport d'étonnement (/50)", "weight": 15, "max": 50}, {"id": "c3", "label": "CC3 — rapport individuel (/40)", "weight": 50, "max": 40}], "formule": "Note /20 = 35 % × (CC1 /40) + 15 % × (CC2 /50) + 50 % × (CC3 /40), ramené sur 20 — pas de 2e chance"}$j$::jsonb where id = 'devenir' and grading is null;
